### ISSUE TITLE
Invalid issuer: Not a service account

### ISSUE THREAD

**Issue by mastix** [german-st/dialogflowv2#2]
Hi,

I've tried to run your node today and ran into the following issue:

> "Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant: Invalid issuer: Not a service account."

I've set up the account correctly - at least I think I did:

![screenshot 2018-12-02 at 14 24 14](https://user-images.githubusercontent.com/1812978/49340304-50467480-f63e-11e8-8e6e-b9a5a589a5db.png)

Any idea what the problem is? Service account has DialogAPI-Client Role.

Thanks in advance!

Sascha

**Comment by german-st** [comment]
Hello @mastix 

I did everything according to the instructions [Create service account DialogflowV2](https://dialogflow.com/docs/reference/v2-auth-setup)

I also gave the role **Dialogflow API Admin**
Try to do everything again in accordance with the instructions and add the role ** Dialogflow API Admin **. 
Maybe this will help.

Write by results. And please tell me, you have Node-RED deployed to Linux?
Thank's.

P.S In the field "Private Key" you can insert the entire contents of the json file, it will remove the extra.

**Comment by mastix** [comment]
Hi @german-st ,

yes, it's a Linux deployment. Does it make a difference? :)

Thanks for the link: Yes, I think I've already followed that guide. I did not install the Google Cloud SDK though - is this necessary for your plugin?

I will give it another shot later today and will let you know the results.

Thanks for your help,

Sascha

**Comment by german-st** [comment]
Thank @mastix . Just before that there was previous Issue an installation error on Linux. Now I'm sure it works)

I had SDK installed. But should work without installing it. You can follow the instruction and do everything before the section "Using the key".
If that doesn't work, try installing the SDK. Also a detail description with screenshots is in Node-RED, if you select our node and go to the Information tab

I hope to help you) Waiting for your answer on the results.
Good luck.

**Comment by mastix** [comment]
Created a new service account with admin rights... and voila: Seems to work now. Thanks for the link!
